---
# This is the main configuration file for go-rtbh.
#
# Description (and defaults):
#
# redis:
#   address: 'localhost:6379'
#   password: ''
#   database: 0
#
# amqp:
#   address: 'localhost:5672'
#   username: 'go-rtbh'
#   password: 'go-rtbh'
#   exchange: 'amqp-input'
#
# whitelist:
#   - name: 'descriptive name for entry'
#     ips:
#       - <ipv4 address of entry>
#       - <ipv6 address of entry>
#

general:
  workers: 8
  reaper_interval: 10s
  resolver:
    enable: true
    max_interval: 2500ms

api:
  bindip: '0.0.0.0'
  bindport: 8080
  resources: ./rtbh-webapp

redis:
  address: 'redis.service.as65342:6379'

postgresql:
  address: 'postgresql.service.as65342:5432'
  username: 'go-rtbh'
  password: 'go-rtbh'
  name: 'go-rtbh'

amqp:
  address: 'rabbitmq.service.as65342:5672'
  username: 'go-rtbh'
  password: 'go-rtbh'
  exchange: 'amqp-input'

elasticsearch:
  address: 'elasticsearch.service.as65342:9200'

bgp:
  asnum: 65342
  routerid: '10.0.4.1'
  nexthop: '192.0.2.1'
  nexthopv6: '2001:db8::2:1'
  community: '65342:666'
  localpref: 100
  peers:
    - name: 'router_protected'
      address: '10.0.4.4'
      asnum: 65342

whitelist:
  - address: '10.0.3.1'
    description: 'development workstation'
  - address: '213.154.229.26'
    description: 'Private colocation server'

blacklist:
  - address: '222.186.56.46'
    reason: 'Known attacker ip'

ruleset:
  - '^ET.*'
  - '^SURICATA.*'
